export const categories = [
  { value: "technology", label: "Technology" },
  { value: "coding", label: "Coding" },
  { value: "programming", label: "Programming" },
  { value: "science", label: "Science" },
  { value: "ai", label: "AI" },
  { value: "health", label: "Health" },
  { value: "blockchain", label: "Blockchain" },
  { value: "crypto", label: "Crypto" },
  { value: "business", label: "Business" },
  { value: "marketing", label: "Marketing" },
  { value: "design", label: "Design" },
  { value: "productivity", label: "Productivity" },
  { value: "motivation", label: "Motivation" },
  { value: "psychology", label: "Psychology" },
  { value: "politics", label: "Politics" },
  { value: "sports", label: "Sports" },
  { value: "entertainment", label: "Entertainment" },
  { value: "travel", label: "Travel" },
  { value: "lifestyle", label: "Lifestyle" },
  { value: "food", label: "Food" },
  { value: "education", label: "Education" },
  { value: "culture", label: "Culture" },
];
